/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamScheduler;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author christendsouza
 */
public class NSAR extends javax.swing.JFrame {
    /**
     * Creates new form NSAR
     */
    public NSAR() {
        initComponents();
    }
   // @Override
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ExamScheduler.ExamSchedulerApp.class).getContext().getResourceMap(NSAR.class);
        Close.setText(resourceMap.getString("Close.text")); // NOI18N
        Close.setName("Close"); // NOI18N
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "NSAR", "NSSR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("jTable1.columnModel.title0")); // NOI18N
        jTable1.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("jTable1.columnModel.title1")); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(91, 91, 91)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(Close)
                .add(135, 135, 135))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 409, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(Close))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
						DriverManager.registerDriver(new com.mysql.jdbc.Driver());
					
						String url="jdbc:mysql://localhost:3306/ExamDB";//?autoReconnect=true&relaxAutoCommit=true";
						
						Connection cn=null;
                                                cn=DriverManager.getConnection(url,"root","210296book");
						Statement st=cn.createStatement();
                                                
                                                String sqlQuery = "select USN from Status where NSAR=1";
                                                
                                                ResultSet rs=st.executeQuery(sqlQuery);
                                                /*JOptionPane.showMessageDialog(null,rs.getString(1));
                                                String sqlQuery2 = "select USN from Status where NSSR=1";
                                                
                                                ResultSet rs2=st.executeQuery(sqlQuery);*/
                                                //String z="";
                                                int i=0;
                                                while(rs.next()) {
                // step through the output data row-by-row
                                                                jTable1.setValueAt(rs.getString(1),i,0);
                                                                i++;
                                                }
                                                /*for (int j = 0; j < i; i++) {
            jTable1.getColumnModel().getColumn(i + 1).setCellRenderer(new FullTableTextAreaRenderer(i));
        }*/
                                                
                                                sqlQuery = "select USN from Status where NSSR=1";
                                                
                                                rs=st.executeQuery(sqlQuery);
                                                /*JOptionPane.showMessageDialog(null,rs.getString(1));
                                                String sqlQuery2 = "select USN from Status where NSSR=1";
                                                
                                                ResultSet rs2=st.executeQuery(sqlQuery);*/
                                                //String z="";
                                                i=0;
                                                while(rs.next()) {
                // step through the output data row-by-row
                                                                jTable1.setValueAt(rs.getString(1),i,1);
                                                                i++;
                                                }
                                                for (int j = 0; j < i; i++) {
            jTable1.getColumnModel().getColumn(i + 1).setCellRenderer(new FullTableTextAreaRenderer(i));
        }
                                                        
                                                
                                            
                                                        
							
							//r=r+s+"\n";
                                                       
						
                                                //model.insertRow(1, new Object[]{r,r,r,r,r});
                                                //model.setValueAt(r, 0, flag);
                                                cn.close();
						
						
						//if(flag==0)
						//{
							
						//}
						//cn.close();
					}
                                        catch(Exception e)
                                        {
                                            //JOptionPane.showMessageDialog(null, "Connection unsuccessful!");
                                            //flag=1;
                                            e.printStackTrace();
                                        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main_NSAR() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NSAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NSAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NSAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NSAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NSAR().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Close;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
